### ISSUE TITLE
Handler is triggered twice in Firefox

### ISSUE THREAD

**Issue by Tyriar** [Tyriar/abbr-touch#13]
Forked from https://github.com/Tyriar/abbr-touch/issues/12#issuecomment-156957149

**Comment by My1** [comment]
is there a way to change the touch to a click handler to check whether the normal Firefox has a similar behavior (and maybe get some logs out of the script console?

**Comment by Tyriar** [comment]
Not happening anymore on Firefox 45.0.2 (desktop) or latest Firefox for Android, closing.
